### ISSUE TITLE
Could not reach any registry endpoint

### ISSUE THREAD

**Issue by jivank** [jperla/pullcontainer-binary#3]
I get the following error:

```
root@workstation:/home/jivan# pulldocker busybox -o mybb
INFO[0000] +job trust_update_base()
INFO[0000] -job trust_update_base() = OK (0)
ERRO[0002] Could not reach any registry endpoint
```

Any ideas?

**Comment by ehsanmostajeran** [comment]
Having the same problem here.

INFO[0000] +job trust_update_base()
INFO[0000] Trust graph fetch failed: Get https://dvjy3tqbc323p.cloudfront.net/trust/official.json: dial tcp: lookup dvjy3tqbc323p.cloudfront.net on [10.1.1.107]:53: no such host
INFO[0000] -job trust_update_base() = OK (0)
ERRO[0004] Could not reach any registry endpoint
Could not reach any registry endpoint
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40361f]

goroutine 16 [running]:
runtime.panic(0x884820, 0xd1c013)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
main.main()
        /go/src/github.com/docker/docker/pulldocker/pulldocker.go:115 +0x17bf

goroutine 19 [finalizer wait]:
runtime.park(0x4165a0, 0xd34848, 0xd1ed89)
        /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xd34848, 0xd1ed89)
        /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
        /usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
        /usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 36 [select]:
net/http.(_persistConn).writeLoop(0xc20824cb00)
        /usr/local/go/src/pkg/net/http/transport.go:885 +0x38f
created by net/http.(_Transport).dialConn
        /usr/local/go/src/pkg/net/http/transport.go:601 +0x957

goroutine 24 [sleep]:
time.Sleep(0x12a05f200)
        /usr/local/go/src/pkg/runtime/time.goc:39 +0x31
net.func·019()
        /usr/local/go/src/pkg/net/dnsclient_unix.go:183 +0x56
created by net.loadConfig
        /usr/local/go/src/pkg/net/dnsclient_unix.go:212 +0x153

goroutine 35 [runnable]:
net/http.(_persistConn).readLoop(0xc20824cb00)
        /usr/local/go/src/pkg/net/http/transport.go:868 +0x829
created by net/http.(_Transport).dialConn
        /usr/local/go/src/pkg/net/http/transport.go:600 +0x93f
